CREATE TABLE `scans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`scanId` varchar(100) NOT NULL,
	`leadId` varchar(50) NOT NULL,
	`businessName` varchar(255) NOT NULL,
	`websiteUrl` varchar(500) NOT NULL,
	`city` varchar(100) NOT NULL,
	`state` varchar(2) NOT NULL,
	`industry` varchar(50) NOT NULL,
	`contactName` varchar(255),
	`contactEmail` varchar(255),
	`schemaScore` int DEFAULT 0,
	`aiCrawlerScore` int DEFAULT 0,
	`technicalSeoScore` int DEFAULT 0,
	`contentSignalsScore` int DEFAULT 0,
	`directoryPresenceScore` int DEFAULT 0,
	`reviewSignalsScore` int DEFAULT 0,
	`overallScore` int DEFAULT 0,
	`grade` varchar(1),
	`topRecommendations` json,
	`fullResponse` json,
	`source` enum('public_form','api','internal') DEFAULT 'public_form',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `scans_id` PRIMARY KEY(`id`),
	CONSTRAINT `scans_scanId_unique` UNIQUE(`scanId`),
	CONSTRAINT `scans_leadId_unique` UNIQUE(`leadId`)
);
