/**
 * llms.txt Generator
 *
 * Generates an llms.txt file following the llmstxt.org specification.
 * This file helps AI crawlers (GPTBot, ClaudeBot, PerplexityBot) understand
 * the most important content on a client's website.
 *
 * Evidence: Triangle IP reported 5x AI traffic increase after implementation.
 * Adopted by 784+ major sites including Anthropic, Stripe, Cloudflare, Vercel.
 * Spec: https://llmstxt.org
 */

import { invokeLLM } from './_core/claude';
import type { Message } from './_core/claude';

export interface LlmsTextInput {
  businessName: string;
  website: string;
  industry: string;
  servicesOffered: string[];
  targetLocation: string;
  businessDescription?: string;
  keyPages?: string[];
}

export interface LlmsTextOutput {
  llmsTxt: string;
  llmsFullTxt: string;
  implementationGuide: string;
  robotsTxtAdditions: string;
}

/**
 * Generate the llms.txt file content for a client's website.
 */
export async function generateLlmsText(input: LlmsTextInput): Promise<LlmsTextOutput> {
  console.log(`[llms.txt Generator] Generating for ${input.businessName}...`);

  // Generate AI-optimized business summary via Claude
  const summaryMessages: Message[] = [
    {
      role: 'system',
      content: `You are an expert at writing concise, factual business descriptions optimized for AI consumption. Write in clear, declarative sentences. No marketing fluff. Focus on: what the business does, where it operates, who it serves, and what makes it notable.`,
    },
    {
      role: 'user',
      content: `Write a 3-4 sentence factual description of this business for an llms.txt file:

Business: ${input.businessName}
Industry: ${input.industry}
Services: ${input.servicesOffered.join(', ')}
Location: ${input.targetLocation}
Website: ${input.website}
${input.businessDescription ? `Additional context: ${input.businessDescription}` : ''}

Requirements:
- Factual, not promotional
- Include location and service area
- Mention key services
- Written for AI systems, not humans`,
    },
  ];

  const summaryResult = await invokeLLM({ messages: summaryMessages });
  const businessSummary = summaryResult.choices[0].message.content.trim();

  // Build the llms.txt file
  const llmsTxt = generateLlmsTxtContent(input, businessSummary);
  const llmsFullTxt = generateLlmsFullTxtContent(input, businessSummary);
  const implementationGuide = generateImplementationGuide(input);
  const robotsTxtAdditions = generateRobotsTxtAdditions(input);

  return {
    llmsTxt,
    llmsFullTxt,
    implementationGuide,
    robotsTxtAdditions,
  };
}

function generateLlmsTxtContent(input: LlmsTextInput, summary: string): string {
  const domain = input.website.replace(/^https?:\/\//, '').replace(/\/$/, '');

  return `# ${input.businessName}

> ${summary}

## About

${input.businessName} is a ${input.industry.toLowerCase()} business serving ${input.targetLocation}.

## Services

${input.servicesOffered.map(s => `- ${s}`).join('\n')}

## Key Pages

- [Home](${input.website})
- [Services](${input.website}/services)
- [About](${input.website}/about)
- [Contact](${input.website}/contact)
${input.keyPages ? input.keyPages.map(p => `- [${p}](${input.website}/${p.toLowerCase().replace(/\s+/g, '-')})`).join('\n') : ''}

## Contact

- Website: ${input.website}
- Location: ${input.targetLocation}

## Service Area

${input.targetLocation}
`;
}

function generateLlmsFullTxtContent(input: LlmsTextInput, summary: string): string {
  return `# ${input.businessName} — Full Context

> ${summary}

## Company Overview

${input.businessName} is a ${input.industry.toLowerCase()} provider based in ${input.targetLocation}. The business offers professional services to individuals and businesses in the area.

## Detailed Services

${input.servicesOffered.map((s, i) => `### ${i + 1}. ${s}

${input.businessName} provides ${s.toLowerCase()} services in ${input.targetLocation}. Contact for details and pricing.
`).join('\n')}

## Service Area & Location

Primary service area: ${input.targetLocation}

## How to Engage

- Visit: ${input.website}
- Services page: ${input.website}/services
- Contact: ${input.website}/contact

## Frequently Asked Topics

- ${input.servicesOffered.slice(0, 3).map(s => `Best ${s.toLowerCase()} in ${input.targetLocation}`).join('\n- ')}
- ${input.industry} services near ${input.targetLocation}
- Professional ${input.industry.toLowerCase()} provider recommendations

---
Generated by SuggestedByGPT AI Visibility Optimization
`;
}

function generateImplementationGuide(input: LlmsTextInput): string {
  const domain = input.website.replace(/^https?:\/\//, '').replace(/\/$/, '');

  return `# llms.txt Implementation Guide

## What is llms.txt?

llms.txt is a standardized file (like robots.txt) that helps AI platforms understand your website's most important content. It provides a structured summary that AI crawlers can quickly parse.

**Adopted by:** Anthropic, Stripe, Cloudflare, Vercel, and 784+ other major sites.

## Files to Deploy

### 1. llms.txt (Required)
Place at: \`${input.website}/llms.txt\`

This is the concise version that AI crawlers read first. Contains your business summary, services, and key page links.

### 2. llms-full.txt (Recommended)
Place at: \`${input.website}/llms-full.txt\`

Extended version with detailed service descriptions and context. Referenced from llms.txt for AI systems that want deeper information.

## Installation Instructions

### WordPress

**Method 1: File Upload (Simplest)**
1. Download both files from your portal
2. Connect to your site via FTP/SFTP (or use File Manager in cPanel)
3. Upload \`llms.txt\` to your site's root directory (same folder as wp-config.php)
4. Upload \`llms-full.txt\` to the same directory
5. Verify: Visit \`${input.website}/llms.txt\` in your browser

**Method 2: WordPress Plugin**
1. Install "LLMs.txt for WordPress" plugin
2. Go to Settings → LLMs.txt
3. Paste the content from the provided llms.txt file
4. Save and publish

### Squarespace

1. Go to Settings → Advanced → Custom Code
2. Unfortunately, Squarespace doesn't support root-level file placement directly
3. **Workaround**: Add a redirect rule pointing /llms.txt to a page with the content
4. Or use Squarespace's developer mode to add the file

### Wix

1. Go to Settings → Custom Code (under Advanced)
2. Upload the file to your site's root directory using Wix's file manager
3. Verify accessibility at ${input.website}/llms.txt

### Shopify

1. Go to Online Store → Themes → Edit Code
2. Create a new template: \`templates/llms-txt.liquid\`
3. Paste the llms.txt content
4. Set up a URL redirect: /llms.txt → the template page

### Static HTML / Custom CMS

1. Place both files in your web root directory
2. Ensure your server serves them as plain text (Content-Type: text/plain)
3. Verify: Visit ${input.website}/llms.txt

## Verification

After deployment, verify by:
1. Opening \`${input.website}/llms.txt\` in your browser — you should see the plain text content
2. Checking \`${input.website}/llms-full.txt\` similarly
3. Ensure both return Content-Type: text/plain (check in browser dev tools → Network tab)

## robots.txt Updates

Add these lines to your robots.txt to ensure AI crawlers can access the files:

\`\`\`
# AI Crawler Access
Allow: /llms.txt
Allow: /llms-full.txt
\`\`\`

## Expected Impact

- **Timeline**: AI crawlers typically index new files within 1-4 weeks
- **Effect**: Improved accuracy when AI platforms describe your business
- **Measurement**: Use AI visibility tracking tools to monitor citation changes

---
*Generated by SuggestedByGPT AI Visibility Optimization*
`;
}

function generateRobotsTxtAdditions(input: LlmsTextInput): string {
  return `# ============================================
# AI Crawler Configuration for ${input.businessName}
# Add these lines to your existing robots.txt
# ============================================

# Allow AI crawlers to access your site
User-agent: GPTBot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Google-Extended
Allow: /

User-agent: Bingbot
Allow: /

# Allow access to llms.txt files
Allow: /llms.txt
Allow: /llms-full.txt

# Sitemap (ensure this is present)
Sitemap: ${input.website}/sitemap.xml
`;
}

/**
 * Format the complete llms.txt deliverable as a markdown report.
 */
export function formatLlmsTextReport(businessName: string, output: LlmsTextOutput): string {
  return `# llms.txt & AI Crawler Optimization Package

**Client:** ${businessName}
**Generated:** ${new Date().toLocaleDateString()}

---

## Why llms.txt Matters

llms.txt is an emerging standard that helps AI platforms (ChatGPT, Claude, Perplexity, Gemini) understand your website quickly and accurately. It's like a "cheat sheet" for AI crawlers.

**Evidence:**
- Adopted by Anthropic (makers of Claude), Stripe, Cloudflare, Vercel
- Triangle IP reported 5x increase in AI-referred traffic after implementation
- Near-zero implementation cost with potential high upside

---

## Your llms.txt File

Deploy this file at: \`/llms.txt\` (root of your website)

\`\`\`
${output.llmsTxt}
\`\`\`

---

## Your llms-full.txt File

Deploy this file at: \`/llms-full.txt\` (root of your website)

\`\`\`
${output.llmsFullTxt}
\`\`\`

---

## robots.txt Additions

Add these lines to your existing robots.txt file to ensure AI crawlers can access your site:

\`\`\`
${output.robotsTxtAdditions}
\`\`\`

---

${output.implementationGuide}
`;
}
